In [3]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import numpy as np
from sklearn.model_selection import train_test_split
digits = load_digits()

In [19]:
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [20]:
Log = LogisticRegression()
Log.fit(X_train,y_train)
Log.score(X_test,y_test)

c:\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [21]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9833333333333333

In [22]:
Rfc = RandomForestClassifier()
Rfc.fit(X_train,y_train)
Rfc.score(X_test,y_test)

0.9740740740740741

In [23]:
from sklearn.model_selection import KFold

In [24]:
kf = KFold(10)

In [25]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9,10,11]):
    print(train_index,test_index)

[ 2  3  4  5  6  7  8  9 10] [0 1]
[ 0  1  3  4  5  6  7  8  9 10] [2]
[ 0  1  2  4  5  6  7  8  9 10] [3]
[ 0  1  2  3  5  6  7  8  9 10] [4]
[ 0  1  2  3  4  6  7  8  9 10] [5]
[ 0  1  2  3  4  5  7  8  9 10] [6]
[ 0  1  2  3  4  5  6  8  9 10] [7]
[ 0  1  2  3  4  5  6  7  9 10] [8]
[ 0  1  2  3  4  5  6  7  8 10] [9]
[0 1 2 3 4 5 6 7 8 9] [10]


In [26]:
def get_score(model , X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [27]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [28]:
log_scores = []
svm_scores = []
rfc_scores = []

for train_index,test_index in kf.split(digits.data):
    X_train,X_test = digits.data[train_index],digits.data[test_index]
    y_train,y_test = digits.target[train_index],digits.target[test_index]
    log_scores.append(get_score(Log,X_train,X_test,y_train,y_test))
    svm_scores.append(get_score(svm,X_train,X_test,y_train,y_test))
    rfc_scores.append(get_score(Rfc,X_train,X_test,y_train,y_test))

c:\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_resu

In [31]:
log_scores

[0.9055555555555556,
 0.9777777777777777,
 0.8777777777777778,
 0.9555555555555556,
 0.9444444444444444,
 0.9666666666666667,
 0.9555555555555556,
 0.9329608938547486,
 0.8770949720670391,
 0.9217877094972067]

In [32]:
svm_scores

[0.9444444444444444,
 1.0,
 0.9333333333333333,
 0.9833333333333333,
 0.9833333333333333,
 0.9888888888888889,
 0.9888888888888889,
 0.994413407821229,
 0.9664804469273743,
 0.9497206703910615]

In [33]:
rfc_scores

[0.9,
 0.9833333333333333,
 0.9333333333333333,
 0.95,
 0.95,
 0.9611111111111111,
 0.9722222222222222,
 0.9553072625698324,
 0.9497206703910615,
 0.9385474860335196]

In [35]:
from sklearn.model_selection import cross_val_score

In [36]:
cross_val_score(Log , digits.data , digits.target)

c:\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_resu

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [37]:
cross_val_score(svm,digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [39]:
cross_val_score(Rfc,digits.data,digits.target)

array([0.925     , 0.91111111, 0.96100279, 0.97214485, 0.92200557])

In [40]:
cross_val_score(RandomForestClassifier(n_estimators=10),digits.data,digits.target)

array([0.90555556, 0.85      , 0.91643454, 0.94707521, 0.89415042])

In [41]:
cross_val_score(RandomForestClassifier(n_estimators=100),digits.data,digits.target)

array([0.92222222, 0.90555556, 0.96100279, 0.97493036, 0.92200557])

In [42]:
cross_val_score(RandomForestClassifier(n_estimators=200),digits.data,digits.target)

array([0.93333333, 0.91111111, 0.95264624, 0.96657382, 0.92200557])

In [43]:
cross_val_score(RandomForestClassifier(n_estimators=150),digits.data,digits.target)

array([0.93888889, 0.91944444, 0.9637883 , 0.96657382, 0.93036212])

In [44]:
cross_val_score(RandomForestClassifier(n_estimators=160),digits.data,digits.target)

array([0.93333333, 0.925     , 0.95543175, 0.94986072, 0.9275766 ])